#ifndef ERRORS_H_
#define ERRORS_H_

// Common error codes
#define SUCCESS 0

// Network communications error codes
#define NETWORK_IS_INACTIVE						1100
#define NETWORK_IS_ACTIVE						1101
#define NETWORK_CONNECTION_START_FAILED			1102
#define NETWORK_CONNECTION_END_FAILED			1103
#define NETWORK_CONNECTION_NOT_SET				1104

#define NETWORK_UNEXPECTED_EVENT_LOOP_FAILURE	1105
#define NETWORK_DATA_RECEIVE_FAILURE			1106

#endif /* ERRORS_H_ */

